# Generated by Django 5.0.3 on 2024-04-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cook",
            options={
                "ordering": ("first_name",),
                "verbose_name": "cooker",
                "verbose_name_plural": "cookers",
            },
        ),
        migrations.AlterModelOptions(
            name="dish",
            options={
                "ordering": ("dish_type__name", "name"),
                "verbose_name": "dish",
                "verbose_name_plural": "dishes",
            },
        ),
        migrations.AlterField(
            model_name="cook",
            name="years_of_experience",
            field=models.IntegerField(default=0),
        ),
    ]
